# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-26 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ljapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcexe',
            name='destenv',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
