# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-26 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ljapps', '0002_funcexe_destenv'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcevent',
            name='result',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='funcevent',
            name='zip',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
