# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-03 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ljapps', '0003_auto_20180426_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcexe',
            name='rollback',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
