# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-06-08 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ljapps', '0005_build_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build_history',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='apps',
            name='urllocation',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
